# Generated by Django 6.0.4 on 2026-04-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_remove_staff_profile_image_alter_staff_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('service', 'Service'), ('delivery', 'Delivery'), ('staff', 'Staff Behaviour'), ('app', 'Application Issue'), ('suggestion', 'Suggestion')], default='Not Specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='Not Specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='courier.package'),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
