# Generated by Django 6.0.4 on 2026-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_feedback_feedback_type_feedback_screenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
