# Generated by Django 6.0.4 on 2026-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_remove_feedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Delivery Staff', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
