# Generated by Django 6.0.4 on 2026-04-19 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_staff_address_staff_profile_image_alter_staff_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
