# Generated by Django 6.0.4 on 2026-04-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
