# Generated by Django 6.0.4 on 2026-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
