# Generated by Django 6.0.2 on 2026-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
