from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('packages/', views.packages_view, name='packages'),
    path('add-package/', views.add_package_view, name='add_package'),
    path('edit-package/<int:package_id>/', views.edit_package_view, name='edit_package'),
    path('delete-package/<int:package_id>/', views.delete_package_view, name='delete_package'),
    path('admin-packages/', views.admin_packages_view, name='admin_packages'),
    path('update-status/<int:package_id>/', views.update_status_view, name='update_status'),
    path('manage-users/', views.manage_users_view, name='manage_users'),
    path('add-user/', views.add_user_view, name='add_user'),
    path('edit-user/<int:user_id>/', views.edit_user_view, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user_view, name='delete_user'),
    path('update-profile/', views.update_profile_view, name='update_profile'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('feedback-list/', views.feedback_list_view, name='feedback_list'),
    path('track-package/', views.track_package_view, name='track_package'),
    path('admin-dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('add-staff/', views.add_staff_view, name='add_staff'),
    path('manage-staff/', views.manage_staff_view, name='manage_staff'),
    path('logout/', views.logout_view, name='logout'),
    path('staff-update-status/<int:package_id>/',views.staff_update_status_view,name='staff_update_status'),
    path('assign-package/<int:package_id>/',views.assign_package_view,name='assign_package'),
    path('add-staff/', views.add_staff_view, name='add_staff'),
    path('manage-staff/', views.manage_staff_view, name='manage_staff'),
    path('edit-staff/<int:staff_id>/', views.edit_staff_view, name='edit_staff'),
    path('delete-staff/<int:staff_id>/', views.delete_staff_view, name='delete_staff'),
    path('staff-update-status/<int:package_id>/',views.staff_update_status_view,name='staff_update_status'),
    path('assign-package-list/',views.assign_package_list_view,name='assign_package_list'),
    path('staff-history/',views.staff_history_view,name='staff_history'),
    path('staff-dashboard/', views.staff_dashboard_view, name='staff_dashboard'),
    path('staff-packages/', views.staff_packages_view, name='staff_packages'),
    path('staff-history/', views.staff_history_view, name='staff_history'),
    path(
    'staff-profile/',
    views.staff_profile_view,
    name='staff_profile'
),
    path("delete-feedback/<int:id>/", views.delete_feedback_view, name="delete_feedback"),
    path('reply-feedback/<int:feedback_id>/', views.reply_feedback_view, name='reply_feedback'),
    path('staff-chat-list/', views.staff_chat_list_view, name='staff_chat_list'),
    path('staff-admin-chat/', views.staff_admin_chat_view, name='staff_admin_chat'),
    path('staff-chat-list/', views.staff_chat_list_view, name='staff_chat_list'),
    path('admin-open-chat/<int:staff_id>/', views.admin_open_chat_view, name='admin_open_chat'),
    path('payment/<int:package_id>/', views.payment_view, name='payment'),
    path('receipt/<int:package_id>/', views.receipt_view, name='receipt'),

]